// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address/add-address": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a shipping address. The ` + "`" + `user_id` + "`" + ` field is taken from the request body and is not checked against the authenticated user, so any authenticated caller can currently attach an address to another user's account. Both the city and the delivery address are required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addresses"
                ],
                "summary": "Add a new address",
                "parameters": [
                    {
                        "description": "Address data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_address_models.UserAddress"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Address added, containing success and message keys",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body, the user does not exist, or the address could not be saved",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate a user with the email and the one-time code sent by ` + "`" + `/auth/send-otp` + "`" + `, and return a JWT access token. The OTP is consumed on success and cannot be reused. Note that the success response contains ` + "`" + `message` + "`" + ` and ` + "`" + `token` + "`" + ` keys only, with no ` + "`" + `success` + "`" + ` key, whereas the error responses use an ` + "`" + `error` + "`" + ` key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with email and OTP",
                "parameters": [
                    {
                        "description": "Email and OTP",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_handler.LoginPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful, containing message and token keys",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body, containing an error key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Incorrect or expired OTP, containing an error key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account as either a customer or a seller. Registering with an email that already exists returns 409. Use a role of ` + "`" + `admin` + "`" + ` only for internal tooling; normal signups should use ` + "`" + `customer` + "`" + ` or ` + "`" + `seller` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_auth_models.RegisterPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account created, containing success and message keys",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body, or an invalid role",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Email is already registered",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Account could not be created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/send-otp": {
            "post": {
                "description": "Send a one-time password to the user's email for verification. The code is valid for five minutes and can only be used once. Note that this endpoint uses two different response envelopes: a 400 returns ` + "`" + `{\"error\": \"...\"}` + "`" + ` while a 500 returns ` + "`" + `{\"success\": false, \"message\": \"...\"}` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Send OTP to email",
                "parameters": [
                    {
                        "description": "Email address",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_handler.SendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent, containing success and message keys",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body, containing an error key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Unknown email, or the code could not be generated, stored, or emailed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/book/list-books": {
            "get": {
                "description": "Get a paginated list of books. The response echoes the ` + "`" + `page` + "`" + ` and ` + "`" + `limit` + "`" + ` actually applied by the server, which may differ from the requested values when out of range. Any service or database error is reported as 404.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "List all books",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Books fetched, containing success, message, the books under data, and the total, page, and limit counts",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Books could not be fetched",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/book/publish-book": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new book listing. Restricted to the ` + "`" + `seller` + "`" + ` and ` + "`" + `admin` + "`" + ` roles; any other authenticated user receives 403. The authenticated user id is taken from the JWT and used as the book owner, so it cannot be spoofed in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Publish a new book",
                "parameters": [
                    {
                        "description": "Book data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_book_models.PublishBookPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Book published, containing success and message keys",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body, or the book could not be saved",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token, or no user identity on the request context",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Authenticated user is not a seller or admin",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "User id on the request context had an unexpected type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "The book service failed to process the request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/book/update-book": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update book details (owner only)\nUpdate the details of a book the authenticated user owns. Only the fields present in the request body are modified. Restricted to the ` + "`" + `seller` + "`" + ` and ` + "`" + `admin` + "`" + ` roles; any other authenticated user receives 403.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Update an existing book",
                "parameters": [
                    {
                        "description": "Updated book data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_book_models.UpdateBookPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Book updated, containing success, message, and the updated book under data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing user identity, invalid request body, or the update failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Authenticated user is not a seller or admin",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "User id on the request context had an unexpected type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/cart/add-to-cart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a quantity of a book to the authenticated user's cart. Quantities are additive: adding the same book twice increments the stored count rather than replacing it. The user id is taken from the JWT, so a caller can only ever modify their own cart.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Add a book to the cart",
                "parameters": [
                    {
                        "description": "Book and quantity to add",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_cart_model.AddToCartPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Book added to cart, containing success and message keys",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "User id on the request context had an unexpected type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/order/list-user-order": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List every order belonging to the authenticated user, including their line items. The authenticated user id is taken from the JWT and cannot be overridden in the request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "List User order",
                "responses": {
                    "202": {
                        "description": "Orders fetched, containing the list of orders under data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Orders could not be fetched",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "User id on the request context had an unexpected type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/order/place-order": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new order with items, payment method, and shipping address. For the ` + "`" + `COD` + "`" + ` payment method the order is created as PENDING. For the ` + "`" + `ESEWA` + "`" + ` method the response additionally carries a signed ` + "`" + `esewa_payload` + "`" + ` that the client must POST to eSewa's payment form; the order stays PENDING until the eSewa callback is confirmed at ` + "`" + `/payment/success` + "`" + `. Prices are always recalculated server-side from the book records, so any price in the request is ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Place a new order",
                "parameters": [
                    {
                        "description": "Order data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_order_models.PlaceOrderPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Order placed, containing the order under data. For ESEWA orders this also includes the signed esewa_payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body, or an unsupported payment method",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Address id or one of the book ids was not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "User id on the request context had an unexpected type, or the order could not be created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payment/failure": {
            "get": {
                "description": "Browser-facing endpoint that eSewa redirects the customer to when they cancel at the payment page or the payment is declined. There is no payment to verify on a cancel, so the attempt is logged and the browser is redirected to the frontend. This endpoint is unauthenticated because the caller is the customer's browser arriving from eSewa.\n\nThe order is deliberately left in the PENDING payment status: a cancelled checkout is not a dead order, and the customer is free to retry with the same transaction uuid.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Handle a cancelled or failed eSewa payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction identifier sent by eSewa (also accepted as transaction_uuid)",
                        "name": "TransactionUuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Failure reason reported by eSewa",
                        "name": "reason",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to FRONTEND_URL/payment-failure",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/payment/success": {
            "get": {
                "description": "Browser-facing endpoint that eSewa redirects the customer to after a payment. It decodes the base64 ` + "`" + `data` + "`" + ` query parameter, verifies the callback signature, confirms the transaction against eSewa's status API, marks the order paid, and redirects the browser to the frontend. This endpoint is unauthenticated because the caller is the customer's browser arriving from eSewa, which cannot present a JWT.\n\nOn success the response is a 302 redirect to ` + "`" + `FRONTEND_URL/payment-success?orderId=\u003ctransaction_uuid\u003e` + "`" + `. On a business failure it is a 302 redirect to ` + "`" + `FRONTEND_URL/payment-failure?reason=\u003creason\u003e` + "`" + `, where reason is one of ` + "`" + `invalid_signature` + "`" + `, ` + "`" + `order_not_found` + "`" + `, ` + "`" + `order_not_payable` + "`" + `, ` + "`" + `amount_mismatch` + "`" + `, ` + "`" + `payment_incomplete` + "`" + `, ` + "`" + `verification_unavailable` + "`" + `, or ` + "`" + `verification_failed` + "`" + `.\n\nA 400 is returned only when the ` + "`" + `data` + "`" + ` parameter itself is missing or undecodable. Replaying this endpoint for an already-paid order is safe: it returns the same success redirect without re-running fulfillment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Confirm an eSewa payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64-encoded JSON callback signed by eSewa",
                        "name": "data",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to FRONTEND_URL/payment-success with the order id as a query parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing or undecodable data parameter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all registered users. Responds with a bare JSON array of user objects; there is no response envelope on this endpoint. Note that a healthy but empty database also returns 500, because the service reports an empty result set as an error.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "responses": {
                    "200": {
                        "description": "List of registered users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_user_models.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Database error, or no users registered yet",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_yogesh4952_ebookstore_internal_address_models.UserAddress": {
            "type": "object",
            "required": [
                "city",
                "delivery_address",
                "user_id"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "delivery_address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_user_models.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_auth_models.RegisterPayload": {
            "type": "object",
            "required": [
                "age",
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "age": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_user_models.Role"
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_book_models.PublishBookPayload": {
            "type": "object",
            "required": [
                "author_name",
                "category",
                "genre",
                "pages",
                "price",
                "publication",
                "title",
                "units"
            ],
            "properties": {
                "author_name": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "cover_page_url": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer",
                    "minimum": 10
                },
                "price": {
                    "type": "number",
                    "minimum": 10
                },
                "publication": {
                    "type": "string"
                },
                "seller_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "maxLength": 60,
                    "minLength": 2
                },
                "units": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_book_models.UpdateBookPayload": {
            "type": "object",
            "required": [
                "book_id",
                "seller_id"
            ],
            "properties": {
                "author_name": {
                    "type": "string"
                },
                "book_id": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "cover_page_url": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer",
                    "minimum": 10
                },
                "price": {
                    "type": "number",
                    "minimum": 10
                },
                "publication": {
                    "type": "string"
                },
                "seller_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "maxLength": 60,
                    "minLength": 2
                },
                "units": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_cart_model.AddToCartPayload": {
            "type": "object",
            "required": [
                "book_id",
                "quantity"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_order_models.OrderItemRequest": {
            "type": "object",
            "required": [
                "book_id",
                "quantity",
                "seller_id"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                },
                "seller_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_order_models.PaymentMethod": {
            "type": "string",
            "enum": [
                "COD",
                "ESEWA"
            ],
            "x-enum-varnames": [
                "PayementCOD",
                "PayementEsewa"
            ]
        },
        "github_com_yogesh4952_ebookstore_internal_order_models.PlaceOrderPayload": {
            "type": "object",
            "required": [
                "items",
                "payment_method",
                "user_address_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_order_models.OrderItemRequest"
                    }
                },
                "payment_method": {
                    "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_order_models.PaymentMethod"
                },
                "user_address_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_yogesh4952_ebookstore_internal_user_models.Role": {
            "type": "string",
            "enum": [
                "admin",
                "customer",
                "seller"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleCustomer",
                "Roleseller"
            ]
        },
        "github_com_yogesh4952_ebookstore_internal_user_models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_yogesh4952_ebookstore_internal_user_models.Role"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_auth_handler.LoginPayload": {
            "type": "object",
            "required": [
                "email",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                }
            }
        },
        "internal_auth_handler.SendOTPRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "EBook Store API",
	Description:      "REST API for the EBook Store platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
